name: ParallelCluster CI

on: [push, pull_request]

jobs:
  security-annotation-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: francesco-giordano/gh-pr-content-checker@refs/heads/wip/v4
      with:
        github-token: ${{github.token}}
        diffDoesNotContain: ".*nosec.*"
#    - name: Check PR
#      uses: pablo-statsig/gh-pr-content-checker@master
#      with:
#        github-token: ${{github.token}}
#        bodyContains: 'Add this'
#        bodyDoesNotContain: "Delete this"
#        diffContains: 'Add this'
#        diffDoesNotContain: "Delete this"
#        diffContainsRegex: '<regex here>'
#        diffDoesNotContainRegex: '<regex here>'
#        maxLinesChanged: 100000
#        maxFilesChanged: 100000
##      # Checkout the repo
##      - uses: actions/checkout@v3.0.2
##        with:
##          fetch-depth: 0 # needed to checkout all branches for this Action to work
##
##      # Check the PR diff using the current branch and the base branch of the PR
##      - uses: GrantBirki/git-diff-action@v1.1.1
##        id: git-diff-action
##
##      # Print the diff in JSON format
##      - name: echo json diff
##        env:
##          DIFF: ${{ steps.git-diff-action.outputs.json-diff }}
##        run: echo $DIFF
##
##      # Print the diff in raw git format
##      - name: echo raw diff
##        env:
##          DIFF: ${{ steps.git-diff-action.outputs.raw-diff }}
##        run: echo $DIFF

#      with:
#        github-token: ${{github.token}}
#        diffDoesNotContainRegex: '.*nosec.*'

#      # Checkout the repo
#      - uses: actions/checkout@v3.0.2
#        with:
#          fetch-depth: 0 # needed to checkout all branches for this Action to work
#
#      # Check the PR diff using the current branch and the base branch of the PR
#      - uses: GrantBirki/git-diff-action@v1.1.1
#        id: git-diff-action
#      - name: echo json diff
#        env:
#          DIFF: ${{ steps.git-diff-action.outputs.json-diff }}
#        run: echo "$DIFF"
#
#      - run: echo '${{ steps.git-diff-action.outputs.json-diff }}' | jq -r '. | select(.type=="GitDiff").files[] | select(.type=="ChangedFile").chunks[].changes[] | select(.type=="AddedLine").content'